services:
  emulator:
    build:
      context: ./
    environment:
      FIRESTORE_PROJECT_ID: "test"
    ports:
      - 8080:8080 # **FIRESTORE_PORT**
      - 5005:5005 # **FIRESTORE_WS_PORT**
      - 4000:4000 # **UI_PORT**
      - 4400:4400 # **UI_PORT**
      - 4500:4500 # **UI_PORT**
