services:
  emulator:
    build:
      context: ./
      dockerfile: ./Dockerfile.emulator
    environment:
      FIRESTORE_PROJECT_ID: "test"
    ports:
      - 8080:8080 # **FIRESTORE_PORT**
      - 5005:5005 # **FIRESTORE_WS_PORT**
      - 4000:4000 # **UI_PORT**
      - 4400:4400 # **UI_PORT**
      - 4500:4500 # **UI_PORT**
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
  api_server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - emulator
    environment:
      GCLOUD_PROJECT: "test"
      PORT: "8000"
      FIRESTORE_EMULATOR_HOST: "emulator:8080"
    ports: ["8000:8080"]
