# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build cmd project

on:
  workflow_dispatch:

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Original version was 1.20

      - name: Build
        run: go build ./cmd/api_data_ingestor #Original configuration was: go build -v ./...

      - name: Store executable
        uses: actions/upload-artifact@v4
        with:
          name: api_data_ingestor
          path: api_data_ingestor

    # We are not testing yet. When we do, uncomment next configuration.
    # - name: Test
    #  run: go test -v ./...
