# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'  # Original version was 1.20

    - name: Build
      run: go build ./cmd/api_data_ingestor  #Original configuration was: go build -v ./...
      # Does this upload the generated executable?

    # We are not testing yet. When we do, uncomment next configuration.
    # - name: Test
    #  run: go test -v ./...



