name: Get card prices

on:
  workflow_dispatch:
  # TO-DO Add the schedule once the workflow's body is complete
  # schedule:
  # - cron: "0 5 * * *"

jobs:
  UpdatePrices:
    name: Update card prices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only csv
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /scripts
            album_season_of_weaving.csv
          sparse-checkout-cone-mode: false
      - name: Get latest succesful build run
        run: |
          ./scripts/save_latest_build_run_to_json.sh
      - name: Save artifact url to environment variable
        run: |
          jq .artifacts_url last_run.json >> "$GITHUB_ENV"
      - name: Get latest executable
        uses: actions/download-artifact@v4
        with:
          name: api_data_ingestor
          path: bin
          github-token: ${{ github.token }}
          run-id: ${{ env.GITHUB_ENV }}

      - name: Execute executable that executes when it's executed
        run: |
          ./bin/api_data_ingestor album_season_of_weaving.csv

      - name: Store card prices
        uses: actions/upload-artifact@v4
        with:
          name: precio_de_cartas.json
          path: precio_de_cartas.json
